In [ ]:
cd drive/My Drive

/content/drive/My Drive


In [ ]:
import pandas as pd
df=pd.read_csv('sample30.csv')

In [ ]:
df.head()

id            brand  ... reviews_username user_sentiment
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3  AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4  AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative

[5 rows x 15 columns]

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import numpy as np
import pandas as pd
import re , nltk , spacy , string
import en_core_web_sm
nlp = en_core_web_sm.load()
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from plotly.offline import plot
import plotly.graph_objects as go
import plotly.express as px
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

In [ ]:
df.shape

(30000, 15)

In [ ]:
df=df.drop(['id', 'brand', 'categories', 'manufacturer', 'name', 'reviews_date',
       'reviews_didPurchase', 'reviews_doRecommend', 'reviews_rating','reviews_userCity','reviews_userProvince','reviews_username'],axis=1)

In [ ]:
df.head()

reviews_text  ... user_sentiment
0  i love this album. it's very good. more to the...  ...       Positive
1  Good flavor. This review was collected as part...  ...       Positive
2                                       Good flavor.  ...       Positive
3  I read through the reviews on here before look...  ...       Negative
4  My husband bought this gel for us. The gel cau...  ...       Negative

[5 rows x 3 columns]

In [ ]:
# checking for null values
df.isnull().sum(axis = 0)

reviews_text        0
reviews_title     190
user_sentiment      1
dtype: int64

In [ ]:
df.user_sentiment.value_counts(normalize=True)

Positive    0.887763
Negative    0.112237
Name: user_sentiment, dtype: float64

In [ ]:
df = df[df['user_sentiment'].notna()]

In [ ]:

df['user_sentiment'] = df['user_sentiment'].map({'Positive':1, 'Negative':0})

In [ ]:
df.head()

reviews_text  ... user_sentiment
0  i love this album. it's very good. more to the...  ...              1
1  Good flavor. This review was collected as part...  ...              1
2                                       Good flavor.  ...              1
3  I read through the reviews on here before look...  ...              0
4  My husband bought this gel for us. The gel cau...  ...              0

[5 rows x 3 columns]

**Text Pre processing**

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
def text_process(msg):
    # 1. all lower case
    # 2. remove punctuation and stopwords
    # 3. lemmatization
    msg = msg.lower()
    nopunct = [char for char in msg if char not in string.punctuation]
    nopunct = ''.join(nopunct)
    a = ''
    list_of_words = nopunct.split()
    for i in range(len(list_of_words)):
        if list_of_words[i] not in stopwords.words('english'):
            b = WordNetLemmatizer().lemmatize(list_of_words[i], pos="v")
            a = a + b + ' '
    a = a.rstrip()
    return a

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
df['reviews_text'] = df['reviews_text'].apply(text_process)

In [ ]:
# splitting the features, X as the text reviews and y as the labels (here user-sentiments)
X = df['reviews_text']
y = df['user_sentiment']

In [ ]:
# 70-30 splitting into training and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
# tf-idf vectorization of the Training Data and transforming the test data
vectorizer = TfidfVectorizer()
tfidf_train = vectorizer.fit_transform(X_train.values.astype('U'))
tfidf_test = vectorizer.transform(X_test.values.astype('U'))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

## **Model** **training**

# Logistics Regression

In [ ]:
clf = LogisticRegression(class_weight = {0: 0.6, 1: 0.4}, random_state = 1)
#5-fold Grid Search Cross Validation
parameters = {'C':[0.01, 0.1, 1, 10, 100]}
folds = 5
grid_search = GridSearchCV(param_grid = parameters, 
                           estimator = clf, 
                           cv = folds,
                           verbose = 3,
                           return_train_score = True)

In [ ]:
grid_search = grid_search.fit(tfidf_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] C=0.01 ..........................................................
[CV] .......... C=0.01, score=(train=0.887, test=0.887), total=   0.1s
[CV] C=0.01 ..........................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV] .......... C=0.01, score=(train=0.887, test=0.887), total=   0.1s
[CV] C=0.01 ..........................................................
[CV] .......... C=0.01, score=(train=0.887, test=0.887), total=   0.1s
[CV] C=0.01 ..........................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV] .......... C=0.01, score=(train=0.887, test=0.887), total=   0.1s
[CV] C=0.01 ..........................................................
[CV] .......... C=0.01, score=(train=0.887, test=0.887), total=   0.2s
[CV] C=0.1 ...........................................................
[CV] ........... C=0.1, score=(train=0.887, test=0.887), total=   0.2s
[CV] C=0.1 ...........................................................
[CV] ........... C=0.1, score=(train=0.887, test=0.887), total=   0.2s
[CV] C=0.1 ...........................................................
[CV] ........... C=0.1, score=(train=0.887, test=0.887), total=   0.3s
[CV] C=0.1 ...........................................................
[CV] ........... C=0.1, score=(train=0.887, test=0.887), total=   0.2s
[CV] C=0.1 ...........................................................
[CV] ........... C=0.1, score=(train=0.887, test=0.887), total=   0.2s
[CV] C=1 .............................................................
[CV] .

[Parallel(n_jobs=1)]: Done  25 out of  25 | elapsed:   13.4s finished


In [ ]:
# getting the best value of hyper-parameter, C
grid_search.best_params_

{'C': 10}

In [ ]:
lr_model = LogisticRegression(C = 10, class_weight = {0: 0.6, 1: 0.4}, random_state = 1234).fit(tfidf_train, y_train)

In [ ]:
# getting the predicted probabilities and predictions for the Training Set
y_train_prob = lr_model.predict_proba(tfidf_train)
y_train_pred = lr_model.predict(tfidf_train)

In [ ]:
y_test_prob = lr_model.predict_proba(tfidf_test)
y_test_pred = [1 if predict_prob >= 0.75 else 0 for predict_prob in y_test_prob[:,1]]

In [ ]:
# computing the accuracy and AUC score for the Training Set and Test Set
training_accuracy = metrics.accuracy_score(y_train, y_train_pred)

fpr, tpr, thresholds = metrics.roc_curve(y_train, y_train_prob[:, 1])
roc_auc = metrics.auc(fpr, tpr)

training_auc = roc_auc


test_accuracy = metrics.accuracy_score(y_test, y_test_pred)

fpr, tpr, thresholds = metrics.roc_curve(y_test, y_test_prob[:,1])
roc_auc = metrics.auc(fpr, tpr)

test_auc = roc_auc

In [ ]:
print("Training Accuracy: ", training_accuracy)
print("Test Accuracy: ", test_accuracy)
print("\n")
print("Training AUC: ", training_auc)
print("Test AUC: ", test_auc)

Training Accuracy:  0.9791894852135816
Test Accuracy:  0.9206666666666666


Training AUC:  0.992561167340978
Test AUC:  0.965357984136827


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.59      0.87      0.71       989
           1       0.98      0.93      0.95      8011

    accuracy                           0.92      9000
   macro avg       0.79      0.90      0.83      9000
weighted avg       0.94      0.92      0.93      9000



In [ ]:
from imblearn.over_sampling import SMOTE
from collections import Counter

# **Multinomial Naive Bayes**

In [ ]:
smote = SMOTE(random_state = 1)
tfidf_train_smote, y_train_smote = smote.fit_resample(tfidf_train, y_train)
# getting the class label distribution in the training data after SMOTe
Counter(y_train_smote)

Counter({0: 18621, 1: 18621})

In [ ]:
nb_clf = MultinomialNB().fit(tfidf_train_smote, y_train_smote)

In [ ]:
y_train_prob = nb_clf.predict_proba(tfidf_train_smote)
y_train_pred = nb_clf.predict(tfidf_train_smote)

In [ ]:
y_test_prob = nb_clf.predict_proba(tfidf_test)
y_test_pred = [1 if predict_prob >= 0.55 else 0 for predict_prob in y_test_prob[:,1]]

In [ ]:
# computing the accuracy and AUC score for the Training Set and Test Set
training_accuracy = metrics.accuracy_score(y_train_smote, y_train_pred)

fpr, tpr, thresholds = metrics.roc_curve(y_train_smote, y_train_prob[:, 1])
roc_auc = metrics.auc(fpr, tpr)

training_auc = roc_auc


test_accuracy = metrics.accuracy_score(y_test, y_test_pred)

fpr, tpr, thresholds = metrics.roc_curve(y_test, y_test_prob[:,1])
roc_auc = metrics.auc(fpr, tpr)

test_auc = roc_auc

In [ ]:
print("Training Accuracy: ", training_accuracy)
print("Test Accuracy: ", test_accuracy)
print("\n")
print("Training AUC: ", training_auc)
print("Test AUC: ", test_auc)

Training Accuracy:  0.909886687073734
Test Accuracy:  0.8263333333333334


Training AUC:  0.9604775072285016
Test AUC:  0.8691332405808544


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.36      0.74      0.48       989
           1       0.96      0.84      0.90      8011

    accuracy                           0.83      9000
   macro avg       0.66      0.79      0.69      9000
weighted avg       0.90      0.83      0.85      9000



In [ ]:
import xgboost as xgb
from xgboost import XGBClassifier

# XG Boost

In [ ]:
# instantiating the XGBoost Classifier with eval_metric as logloss and considered is the SMOTe Over-sampled Training Data
clf = XGBClassifier(eval_metric = 'logloss', random_state = 1234)
# performing 5-fold Grid Search Cross Validation for tuning the hyper-parameters, learning rate and subsample
parameters = {'learning_rate': [0.2, 0.6], 
             'subsample': [0.3, 0.6, 0.9]}
folds = 5
grid_search = GridSearchCV(param_grid = parameters, 
                           estimator = clf, 
                           cv = folds,
                           verbose = 3,
                           return_train_score = True)

In [ ]:
grid_search = grid_search.fit(tfidf_train_smote, y_train_smote)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] learning_rate=0.2, subsample=0.3 ................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  learning_rate=0.2, subsample=0.3, score=(train=0.914, test=0.886), total=   6.6s
[CV] learning_rate=0.2, subsample=0.3 ................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.8s remaining:    0.0s


[CV]  learning_rate=0.2, subsample=0.3, score=(train=0.906, test=0.898), total=   6.2s
[CV] learning_rate=0.2, subsample=0.3 ................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   13.3s remaining:    0.0s


[CV]  learning_rate=0.2, subsample=0.3, score=(train=0.904, test=0.895), total=   6.3s
[CV] learning_rate=0.2, subsample=0.3 ................................
[CV]  learning_rate=0.2, subsample=0.3, score=(train=0.905, test=0.907), total=   6.4s
[CV] learning_rate=0.2, subsample=0.3 ................................
[CV]  learning_rate=0.2, subsample=0.3, score=(train=0.904, test=0.904), total=   6.3s
[CV] learning_rate=0.2, subsample=0.6 ................................
[CV]  learning_rate=0.2, subsample=0.6, score=(train=0.915, test=0.886), total=   8.0s
[CV] learning_rate=0.2, subsample=0.6 ................................
[CV]  learning_rate=0.2, subsample=0.6, score=(train=0.910, test=0.900), total=   7.9s
[CV] learning_rate=0.2, subsample=0.6 ................................
[CV]  learning_rate=0.2, subsample=0.6, score=(train=0.906, test=0.898), total=   8.0s
[CV] learning_rate=0.2, subsample=0.6 ................................
[CV]  learning_rate=0.2, subsample=0.6, score=(train

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:  3.8min finished


In [ ]:
grid_search.best_params_

{'learning_rate': 0.6, 'subsample': 0.9}

In [ ]:
# re-training the XGBoost Model on the SMOTe Over-sampled Training Set with the best values of hyper-parameters
xgb_model = XGBClassifier(eval_metric = 'logloss', 
                          learning_rate = 0.6, 
                          subsample = 0.9, 
                          random_state = 1234).fit(tfidf_train_smote, y_train_smote)

In [ ]:
# getting the predicted probabilities and predictions for the Training Set
y_train_prob = xgb_model.predict_proba(tfidf_train_smote)
y_train_pred = xgb_model.predict(tfidf_train_smote)

In [ ]:
y_test_prob = xgb_model.predict_proba(tfidf_test)
y_test_pred = [1 if predict_prob >= 0.45 else 0 for predict_prob in y_test_prob[:,1]]

In [ ]:
training_accuracy = metrics.accuracy_score(y_train_smote, y_train_pred)

fpr, tpr, thresholds = metrics.roc_curve(y_train_smote, y_train_prob[:, 1])
roc_auc = metrics.auc(fpr, tpr)

training_auc = roc_auc


test_accuracy = metrics.accuracy_score(y_test, y_test_pred)

fpr, tpr, thresholds = metrics.roc_curve(y_test, y_test_prob[:,1])
roc_auc = metrics.auc(fpr, tpr)

test_auc = roc_auc

In [ ]:
print("Training Accuracy: ", training_accuracy)
print("Test Accuracy: ", test_accuracy)
print("\n")
print("Training AUC: ", training_auc)
print("Test AUC: ", test_auc)

Training Accuracy:  0.9516137694001396
Test Accuracy:  0.9156666666666666


Training AUC:  0.9904225766180763
Test AUC:  0.9520732930542042


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.58      0.83      0.68       989
           1       0.98      0.93      0.95      8011

    accuracy                           0.92      9000
   macro avg       0.78      0.88      0.82      9000
weighted avg       0.93      0.92      0.92      9000



In [ ]:
import joblib
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import pairwise_distances

**Logistics regression is the best**

In [ ]:
# saving the tf-idf vectorizer model object
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']

In [ ]:
# saving the logistic regression model object
joblib.dump(lr_model, 'lr_model.pkl')

['lr_model.pkl']

In [ ]:
# saving the predicted sentiments by the model for the whole dataset
tfidf_text = vectorizer.transform([review for review in df['reviews_text'].values.astype('U')])
df['predicted_user_sentiment'] = lr_model.predict(tfidf_text)

In [ ]:
 #saving the final dataframe containing predicted sentiments
df.to_csv('sample30_final.csv', index = False)

# Building Recommendation Engine

In [ ]:
# re-loading the whole dataset
df = pd.read_csv('sample30.csv')

In [ ]:
# displaying the first 5 rows of the dataset
df.head()

id            brand  ... reviews_username user_sentiment
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3  AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4  AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative

[5 rows x 15 columns]

In [ ]:
ratings = df.loc[:, ['reviews_username', 'name', 'reviews_rating']]

In [ ]:
ratings.head()

reviews_username                                        name  reviews_rating
0           joshua   Pink Friday: Roman Reloaded Re-Up (w/dvd)               5
1        dorothy w  Lundberg Organic Cinnamon Toast Rice Cakes               5
2        dorothy w  Lundberg Organic Cinnamon Toast Rice Cakes               5
3          rebecca            K-Y Love Sensuality Pleasure Gel               1
4        walker557            K-Y Love Sensuality Pleasure Gel               1

In [ ]:
ratings.shape

(30000, 3)

In [ ]:
#To avoid repetition
grouped_ratings = ratings.groupby(['reviews_username', 'name'])['reviews_rating'].mean()
ratings = grouped_ratings.reset_index()

In [ ]:
ratings.shape

(27588, 3)

In [ ]:
# 70-30 splitting into training and test data
train, test = train_test_split(ratings, test_size=0.30, random_state=1)

# User-User Recommendation System

In [ ]:
df_pivot = train.pivot(index='reviews_username',
                       columns='name',
                       values='reviews_rating')
df_pivot.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00sab00                                                         NaN              ...                                       NaN
01impala                                                        NaN              ...                                       NaN
02deuce                                                         NaN              ...                                       NaN
0325home                                                        NaN              ...                                       NaN
08dallas                                                        NaN              ...                                       NaN

[5 rows x 251 columns]

In [ ]:
# copying the train dataset into dummy_train
dummy_train = train.copy()

In [ ]:
# the products not rated by user is marked as 1 for prediction and those already rated are marked 0
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [ ]:
# Convert the dummy train dataset into matrix format in which columns are products and the rows are usernames
dummy_train = dummy_train.pivot(index='reviews_username',
                                columns='name',
                                values='reviews_rating').fillna(1)
dummy_train.head(3)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00sab00                                                         1.0              ...                                       1.0
01impala                                                        1.0              ...                                       1.0
02deuce                                                         1.0              ...                                       1.0

[3 rows x 251 columns]

In [ ]:
# subtracting the ratings from their respective mean for each user
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [ ]:
# calculating user correlation using adjusted cosine
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
# replacing the NaN correlation values by 0
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# replacing the negative correlation values by 0
user_correlation[user_correlation<0]=0
user_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# predicting user ratings
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# getting the final user predicted ratings
user_final_rating = np.multiply(user_predicted_ratings, dummy_train)
user_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00sab00                                                         0.0              ...                                       0.0
01impala                                                        0.0              ...                                       0.0
02deuce                                                         0.0              ...                                       0.0
0325home                                                        0.0              ...                                       0.0
08dallas                                                        0.0              ...                                       0.0

[5 rows x 251 columns]

In [ ]:
# taking the username as input
user_input = input("Enter your username: ")

Enter your username: angela


In [ ]:
# recommending top 5 products to the user 
user_final_rating.loc[user_input].sort_values(ascending=False)[0:5]

name
Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd    4.632007
Mike Dave Need Wedding Dates (dvd + Digital)                       2.500000
Red (special Edition) (dvdvideo)                                   2.500000
My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Digital)               2.398508
Yes To Carrots Nourishing Body Wash                                2.132007
Name: angela, dtype: float64

# Evaluation of User-User Model

In [ ]:
# finding out the users common to test and train dataset
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(1068, 3)

In [ ]:
common.head()

reviews_username  ... reviews_rating
292              aaron  ...            5.0
2512             betsy  ...            5.0
20278          patrick  ...            5.0
14985        leslie316  ...            5.0
17442           mickey  ...            5.0

[5 rows x 3 columns]

In [ ]:
# converting into the user-product matrix.
common_user_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [ ]:
common_user_based_matrix.shape

(905, 112)

In [ ]:
user_correlation_df = pd.DataFrame(user_correlation)

In [ ]:
user_correlation_df['reviews_username'] = df_subtracted.index
user_correlation_df.set_index('reviews_username',inplace=True)
user_correlation_df.head()

0      1      2      3      ...  17852  17853  17854  17855
reviews_username                              ...                            
00sab00             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
01impala            0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
02deuce             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
0325home            0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
08dallas            0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 17856 columns]

reviews_username              name  reviews_rating
292            aaron  Equals (blu-Ray)             5.0

In [ ]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_subtracted.index.tolist()

user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [ ]:
user_correlation_df_1.shape

(905, 17856)

In [ ]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [ ]:
user_correlation_df_3 = user_correlation_df_2.T

In [ ]:
user_correlation_df_3.head()

00sab00  1234  123charlie  50cal  ...  yummy  yvonne  zippy  zmom
reviews_username                                    ...                            
00sab00               0.0   0.0         0.0    0.0  ...    0.0     0.0    0.0   0.0
1234                  0.0   0.0         0.0    0.0  ...    0.0     0.0    0.0   0.0
123charlie            0.0   0.0         0.0    0.0  ...    0.0     0.0    0.0   0.0
50cal                 0.0   0.0         0.0    0.0  ...    0.0     0.0    0.0   0.0
aaron                 0.0   0.0         0.0    0.0  ...    0.0     0.0    0.0   0.0

[5 rows x 905 columns]

In [ ]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.73205081, 0.        , 0.42640143, ..., 0.38463733, 5.37379226,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
# preparing the dummy test dataset in a way such that for rated products, the rating is 1, else 0

dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').fillna(0)

In [ ]:
dummy_test.head()

name              100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                       ...                                          
00sab00                                           0.0  ...                                       0.0
1234                                              0.0  ...                                       0.0
123charlie                                        0.0  ...                                       0.0
50cal                                             0.0  ...                                       0.0
aaron                                             0.0  ...                                       0.0

[5 rows x 112 columns]

In [ ]:
# convering the common dataframe into user-product matrix
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [ ]:
common_user_predicted_ratings.head(2)

name              100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                       ...                                          
00sab00                                           0.0  ...                                       0.0
1234                                              0.0  ...                                       0.0

[2 rows x 112 columns]

In [ ]:
# copying the common user predicted ratings
X  = common_user_predicted_ratings.copy() 
X = X[X>0]

# copying the common user predicted ratings
scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [ ]:
# convering the common dataframe into user-product matrix
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [ ]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [ ]:
# calculating RMSE score
rmse = ((((common_ - y)**2).sum(skipna = True)).sum(skipna = True)/total_non_nan)**0.5
print('Root Mean Square Error of the User-based Recommender: ', rmse)

Root Mean Square Error of the User-based Recommender:  2.604243825381424


# Item-Item Based Recommender System

In [ ]:
# Pivoting the train ratings' dataset into matrix format in which columns are usernames and the rows are products.
df_pivot = train.pivot(index='reviews_username',
                       columns='name',
                       values='reviews_rating').T

df_pivot.head()

reviews_username                                    00sab00  ...  zzz1127
name                                                         ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...      NaN  ...      NaN
100:Complete First Season (blu-Ray)                     NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...      NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                  NaN  ...      NaN
42 Dual Drop Leaf Table with 2 Madrid Chairs"           NaN  ...      NaN

[5 rows x 17856 columns]

In [ ]:
# subtracting the ratings from their respective mean for each product
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [ ]:
df_subtracted.head()

reviews_username                                    00sab00  ...  zzz1127
name                                                         ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...      NaN  ...      NaN
100:Complete First Season (blu-Ray)                     NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...      NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                  NaN  ...      NaN
42 Dual Drop Leaf Table with 2 Madrid Chairs"           NaN  ...      NaN

[5 rows x 17856 columns]

In [ ]:
# calculating item correlation using adjusted cosine
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.          0.         ... -0.00613713  0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.         -0.00613713  0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]


In [ ]:
# replacing the negative correlation values by 0
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
# predicting item ratings
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00181451,
        0.01420623],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00241935,
        0.01894165],
       ...,
       [0.        , 0.        , 0.        , ..., 0.0031839 , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.01190624,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00254712, 0.        ,
        0.        ]])

In [ ]:
# getting the final item predicted ratings 
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00sab00                                                         0.0              ...                                  0.000000
01impala                                                        0.0              ...                                  0.014206
02deuce                                                         0.0              ...                                  0.018942
0325home                                                        0.0              ...                                  0.000000
08dallas                                                        0.0              ...                                  0.000000

[5 rows x 251 columns]

In [ ]:
# taking the username as input
user_input = input("Enter your username: ")

Enter your username: angela


In [ ]:
# recommending top 5 products to the user 
item_final_rating.loc[user_input].sort_values(ascending=False)[0:5]

name
Clorox Disinfecting Bathroom Cleaner                                  0.280301
Pleasant Hearth Diamond Fireplace Screen - Espresso                   0.082677
K-Y Love Sensuality Pleasure Gel                                      0.082336
Stander Pt Bedcane - Bed Handle                                       0.072484
L'oreal Paris Advanced Hairstyle Boost It High Lift Creation Spray    0.053380
Name: angela, dtype: float64

# Evaluation

In [ ]:
# finding out the products common to test and train dataset
common =  test[test.name.isin(train.name)]
common.shape

(8255, 3)

In [ ]:
common.head()

reviews_username  ... reviews_rating
16920        mcsquared  ...            5.0
292              aaron  ...            5.0
2512             betsy  ...            5.0
22360            sally  ...            5.0
20278          patrick  ...            5.0

[5 rows x 3 columns]

In [ ]:
# converting into the product-user matrix.
common_item_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [ ]:
item_correlation_df = pd.DataFrame(item_correlation)

In [ ]:
item_correlation_df['name'] = df_subtracted.index
item_correlation_df.set_index('name',inplace=True)
item_correlation_df.head()

0    1    ...  249  250
name                                                          ...          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  1.0  0.0  ...  0.0  0.0
100:Complete First Season (blu-Ray)                 0.0  1.0  ...  0.0  0.0
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  ...  0.0  0.0
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  ...  0.0  0.0
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  ...  0.0  0.0

[5 rows x 251 columns]

In [ ]:
list_name = common.name.tolist()

In [ ]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [ ]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [ ]:
item_correlation_df_3.head()

100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
name                                                                                     ...                                          
100:Complete First Season (blu-Ray)                                                 1.0  ...                                       0.0
2017-2018 Brownline174 Duraflex 14-Month Planne...                                  0.0  ...                                       0.0
2x Ultra Era with Oxi Booster, 50fl oz                                              0.0  ...                                       0.0
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                   0.0  ...                                       0.0
Africa's Best No-Lye Dual Conditioning Relaxer ...                                  0.0  ...                                       0.0

[5 rows x 196 columns]

In [ ]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01449562],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.02386432, 0.        , 0.        , ..., 0.04048669, 0.        ,
        0.        ],
       [0.        , 0.00714374, 0.00302418, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02367706, ..., 0.        , 0.00055568,
        0.        ]])

In [ ]:
# preparing the dummy test dataset in a way such that for rated products, the marking is 1, else 0

dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

In [ ]:
# convering the common dataframe into product-user matrix
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [ ]:
# copying the common item predicted ratings
X  = common_item_predicted_ratings.copy() 
X = X[X>0]
# scaling the ratings between 1 and 5
scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [ ]:
# finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [ ]:
# calculating RMSE score
rmse = ((((common_ - y)**2).sum(skipna = True)).sum(skipna = True)/total_non_nan)**0.5
print('Root Mean Square Error of the User-based Recommender: ', rmse)

Root Mean Square Error of the User-based Recommender:  3.5613878480603836


# User-Based Model is the best one

In [ ]:
user_final_rating.to_csv('user_final_rating.csv')

In [ ]:
# taking the username as input.
user_input = input("Enter your username: ")
if user_input not in list(user_final_rating.index):
    print('Sorry !!! The username is not registered !!!')

Enter your username: angela


In [ ]:
# recommending top 20 products to the user
recommended_user_based_products = pd.DataFrame(user_final_rating.loc[user_input].sort_values(ascending=False))[0:20]

In [ ]:
recommended_user_based_products

angela
name                                                        
Godzilla 3d Includes Digital Copy Ultraviolet 3...  4.632007
Mike Dave Need Wedding Dates (dvd + Digital)        2.500000
Red (special Edition) (dvdvideo)                    2.500000
My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Dig...  2.398508
Yes To Carrots Nourishing Body Wash                 2.132007
L'oreal Paris Advanced Hairstyle Boost It High ...  1.767767
Bi-O-kleen Spray & Wipe All Purpose Cleaner         1.414214
Hormel Chili, No Beans                              1.414214
Clorox Disinfecting Wipes Value Pack Scented 15...  1.020621
Burt's Bees Lip Shimmer, Raisin                     1.020621
Pendaflex174 Divide It Up File Folder, Multi Se...  0.816497
Happy Tot Apple and Butternut Squash                0.000000
Greyson Vintage Industrial Occasional Cocktail ...  0.000000
Gain Original Scent Liquid Fabric Softener 129 Oz   0.000000
Fiskars174 Classic Stick Rotary Cutter (45 Mm)      0.000000
Finish Quantum Dishwasher Detergent, Lemon Spar...  0.000000
Finish Gelpacs Dishwasher Detergent, Orange Sce...  0.000000
Feit 60-Watt A19 Gu24 Base Led Light Bulb - Sof...  0.000000
Equals (blu-Ray)                                    0.000000
Eagle Fat Free Sweetened Condensed Milk             0.000000

In [ ]:
import string

**Fine-tuning the Recommender Model using the Sentiment Analyzer**

In [ ]:
df_predicted_user_sentiments = pd.read_csv('sample30_final.csv') # reading the dataframe having predicted ratings by sentiment analyzer

positive_products = []
for product in recommended_user_based_products.index:
    predicted_sentiments = np.array(df_predicted_user_sentiments.loc[df_predicted_user_sentiments.name == product, 'predicted_user_sentiment'])
    final_sentiment = Counter(predicted_sentiments).most_common()[0][0]
    if final_sentiment == 1:
        positive_products.append(product)
    if len(positive_products) == 5:
        break

AttributeError: ignored

In [ ]:
# getting the 5 final recommended product details like brand, categories and manufacturer along with the name
recommended_user_based_product_details = {}
recommended_user_based_product_details['name'] = []
recommended_user_based_product_details['brand'] = []
recommended_user_based_product_details['categories'] = []
recommended_user_based_product_details['manufacturer'] = []

for products in positive_products:
    recommended_user_based_product_details['brand'].append(df.loc[df.name == products, 'brand'].iloc[0])
    recommended_user_based_product_details['categories'].append(df.loc[df.name == products, 'categories'].iloc[0])
    recommended_user_based_product_details['manufacturer'].append(df.loc[df.name == products, 'manufacturer'].iloc[0])
    recommended_user_based_product_details['name'].append(products)    

In [ ]:
pd.DataFrame(recommended_user_based_product_details)

Empty DataFrame
Columns: [name, brand, categories, manufacturer]
Index: []